# Generated by Django 4.2.3 on 2023-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Назва')),
                ('anons', models.CharField(max_length=260, verbose_name='Опис')),
                ('full_text', models.TextField(verbose_name='Стаття')),
                ('date', models.TimeField(verbose_name='Дата Публікації')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
