# Generated by Django 4.2.3 on 2023-08-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_remove_forum_publications_anons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_publications',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
