# Generated by Django 4.2.3 on 2023-08-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0004_alter_forum_publications_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
